<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerPQwpw4r\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerPQwpw4r/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerPQwpw4r.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerPQwpw4r\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerPQwpw4r\App_KernelDevDebugContainer([
    'container.build_hash' => 'PQwpw4r',
    'container.build_id' => '44aa23d8',
    'container.build_time' => 1728941934,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerPQwpw4r');
